python_library(
    name='targets',
    sources = [
        '__init__.py',
        'base.py',
        'gendeb.py',
        'genrule.py',
        'pkgfilegroup.py',
        'unimplemented.py',
        'virtual.py',
        ],
    dependencies = [
        pants('3rdparty/python:networkx'),
        ],
    )
