python_library(
    name = 'getvar',
    sources = ['python_getvar.py'],
    )

python_binary(
    name = 'python_getvar',
    dependencies = [pants(':getvar')],
    source = 'python_getvar.py',
    )
